### PR TITLE
Test framework

### PR DESCRIPTION
**Pull request by willcl-ark**
Add pytest framework to the project. This will enable safer commits and updates in the future by enabling automatic testing of each RPC after every commit.

NOTE:
This branch includes a few commits to the main lnd_grpc.py module:
> send_to_route_generator() - https://github.com/willcl-ark/lnd_grpc/commit/d7b8e707b9deb07613b99579ca6e50b7b489a334
> send_to_route() - https://github.com/willcl-ark/lnd_grpc/commit/c5055c6cbea7a5c4e779d88bcae971505a07b35f
> send_to_route_sync() - https://github.com/willcl-ark/lnd_grpc/commit/57665c79e617dbbe9dfc6d4c1fda0ce54d8ae562
> subscribe_channel_events() - https://github.com/willcl-ark/lnd_grpc/commit/423becda2c697dbf0bf6f49fed4ec0bdbe9114e9
> get_node_info() - now returns response.routes directly
> Reformatting of the imports

To test, pull and switch to test_framework branch, place an LND symlink or binary in lnd_grpc/bin folder (next to the readme file) and follow the instructions in test.md

### CODE REVIEW

**Comment by willcl-ark** [comment]
@PierreRochard could you confirm that the commits affecting the primary lnd_grpc.py module (noted above in the main PR comment) are not going to break anything for you, then I am going to get this merged.

**Comment by PierreRochard** [comment]
I'll take a look. The pull request has these cache files in it btw `core/__pycache__/serialize.cpython-37.pyc`

**Comment by willcl-ark** [comment]
God damn it I thought I got rid of all that crap already ☺️

**Comment by PierreRochard** [comment]
Just FYI still seeing pycache action

image

**Comment by willcl-ark** [comment]
@PierreRochard those should all be purged now

**Pull request merged**
